// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'Insert API Key here',
    appId: '1:707229519679:android:94e355a225e348b0a90d8a',
    messagingSenderId: '707229519679',
    projectId: 'flutter-chat-app-24472',
    storageBucket: 'flutter-chat-app-24472.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'Insert API Key here',
    appId: '1:707229519679:ios:470b861ef7eb6091a90d8a',
    messagingSenderId: '707229519679',
    projectId: 'flutter-chat-app-24472',
    storageBucket: 'flutter-chat-app-24472.appspot.com',
    iosClientId: '707229519679-kk0ij26edk4bej7gt5rls2q8d8qf3nls.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
